### ISSUE TITLE
snowflake table naming issue with default config 

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_pendo#6]
Hi there, I noticed that out of the box a table is not compatible with Snowflake.  To resolve this a config can easily be added for snowflake not to choke on the table called 'group'

pendo_source:
    group: '"VAULT_DB"."PENDO"."GROUP"' 
 
I'm wondering if there is appetite to fix this so that the default works out of the box?  Happy to implement this with some guidance.  May be its just a simple addition to the readme but there might be a better way this can be addressed?

**Comment by fivetran-jamie** [comment]
^ actually just updated this branch because i was not converting `group` to uppercase for snowflake as well
